server:
  port: ${SERVER_PORT}
spring:
  webflux:
    base-path: /api
  application:
    name: challenge
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    redis:
      connect-timeout: 6000
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  r2dbc:
    pool:
      enabled: true
      initial:
        size: 5
      max-size: 10
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
redis:
  cache:
    key: ${REDIS_CACHE_KEY}
    percent:
      valid: ${REDIS_PERCENT_VALID}
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

resilience4j:
  ratelimiter:
    instances:
      percent-controller:
        limit-for-period: 3
        limit-refresh-period: 1m
        timeout-duration: 5s
        register-health-indicator: true
  circuitbreaker:
    instances:
      getPercentCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
  instances:
    getPercentRetry:
      maxAttempts: 3
      waitDuration: 2s

percent:
  url: ${PERCENT_CLIENT_URL}